### ISSUE TITLE
Requirement on typeguard `2.*` is too strict

### ISSUE THREAD

**Issue by jamescooke** [asphalt-framework/asphalt#80]
## Current behaviour

Current requirement for typeguard is:

```
typeguard ~= 2.0
```

However, this release identifier prevents any newer `3.*` or `4.*` versions of typeguard from being installed into the same environment and makes it hard to use asphalt with other packages that require newer typeguard versions. (`typeguard==3.0.0` was release in March 2023 https://pypi.org/project/typeguard/3.0.0/ and version 4 is available.)

## Expected behaviour

Please could the `pyproject.toml` here: https://github.com/asphalt-framework/asphalt/blob/6e2b50e2af6e7dc56ecbfedbd8c2f5eb609ca7c9/pyproject.toml#L33 be changed to something like `typeguard >= 2.0` ? If there are particular uses of typeguard that require the `<3.0` API, then those would need to be upgraded.

This would allow for packages using newer versions of typeguard to be installed into environments along with asphalt, which is currently not possible.

See also conversation on https://github.com/jupyter/jupyter_core/pull/353#issuecomment-1563166353 👈🏻 in which the suggestion was made to try [Jupyverse](https://github.com/jupyter-server/jupyverse) which in turn uses asphalt.

**Comment by agronholm** [comment]
I hadn't done anything about this because the function used in Asphalt (`check_argument_types()`) is gone in v3.0 and later, replaced by better alternatives. My WIP 5.0 code already did away with the `typeguard` dependency altogether, but I was thinking of using Pydantic 2.0 as a more suitable alternative, as it would allow for more sophisticated validation and documentation of configuration. I understand why you're asking for this, but if I am to do anything about this in Asphalt 4, it would most likely be to remove any uses of `typeguard` altogether.

**Comment by agronholm** [comment]
If you can thumbs up the linked PR, I can merge it and get a release out soon.

**Comment by agronholm** [comment]
I've released v4.12.0 which does away with the typeguard dependency.
